apiVersion: batch/v1
kind: CronJob
metadata:
  name: chute-autoscaler-dryrun
  labels:
    {{- include "chuteAutoscalerDryrun.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.chuteAutoscaler.dryrunSchedule | default "*/2 * * * *" | quote }}
  suspend: {{ .Values.chuteAutoscaler.dryrunSuspend | default false }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      backoffLimit: 2
      ttlSecondsAfterFinished: 15000
      activeDeadlineSeconds: 300
      template:
        metadata:
          labels:
            {{- include "chuteAutoscalerDryrun.labels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          securityContext:
            {{- include "chutes.podSecurityContext" . | nindent 12 }}
          tolerations:
            {{- include "chutes.defaultTolerations" . | nindent 12 }}
            {{- with .Values.chuteAutoscaler.tolerations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.chuteAutoscaler.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.chuteAutoscaler.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
            {{- include "chutes.redisCacertVolume" . | nindent 12 }}
          containers:
            - name: chute-autoscaler-dryrun
              image: {{ include "chutes.image" (list . .Values.chuteAutoscaler.image) | quote }}
              imagePullPolicy: {{ .Values.chuteAutoscaler.imagePullPolicy }}
              securityContext:
                {{- include "chutes.containerSecurityContext" . | nindent 16 }}
              command:
                - uv
                - run
                - python
                - chute_autoscaler.py
                - --soft
              env:
                {{- include "chutes.cronjobEnv" . | nindent 16 }}
                - name: PROMETHEUS_URL
                  value: {{ .Values.chuteAutoscaler.prometheusUrl | default "http://prometheus.chutes.svc.cluster.local:9090" | quote }}
              volumeMounts:
                {{- include "chutes.redisCacertMount" . | nindent 16 }}
              resources:
                {{- include "chutes.cronjobResources" .Values.chuteAutoscaler.resources | nindent 16 }}
