apiVersion: batch/v1
kind: CronJob
metadata:
  name: balance-refresher
  labels:
    {{- include "balanceRefresher.labels" . | nindent 4 }}
    {{- include "chutes.dbAccess" . | nindent 4 }}
    {{- include "chutes.redisAccess" . | nindent 4 }}
spec:
  schedule: {{ .Values.balanceRefresher.schedule | default "* * * * *" | quote }}
  suspend: {{ .Values.balanceRefresher.suspend | default false }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      backoffLimit: 2
      ttlSecondsAfterFinished: 15000
      activeDeadlineSeconds: 300
      template:
        metadata:
          labels:
            {{- include "balanceRefresher.labels" . | nindent 12 }}
            {{- include "chutes.dbAccess" . | nindent 12 }}
            {{- include "chutes.redisAccess" . | nindent 12 }}
        spec:
          restartPolicy: Never
          securityContext:
            {{- include "chutes.podSecurityContext" . | nindent 12 }}
          tolerations:
            {{- include "chutes.defaultTolerations" . | nindent 12 }}
            {{- with .Values.balanceRefresher.tolerations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.balanceRefresher.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.balanceRefresher.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: balance-refresher
              image: {{ include "chutes.image" (list . .Values.balanceRefresher.image) | quote }}
              imagePullPolicy: {{ .Values.balanceRefresher.imagePullPolicy }}
              securityContext:
                {{- include "chutes.containerSecurityContext" . | nindent 16 }}
              command:
                - uv
                - run
                - python
                - balance_refresher.py
              env:
                {{- include "chutes.cronjobEnv" . | nindent 16 }}
              resources:
                {{- include "chutes.cronjobResources" .Values.balanceRefresher.resources | nindent 16 }}
