{{- if .Values.quotaRedis.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: quota-redis-network-policy
  labels:
    {{- include "quotaRedis.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "quotaRedis.labels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              redis-access: "true"
      ports:
        - protocol: TCP
          port: {{ .Values.quotaRedis.service.port }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app: prometheus-redis-exporter
      ports:
        - protocol: TCP
          port: {{ .Values.quotaRedis.service.port }}
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
