apiVersion: v1
kind: Service
metadata:
  name: registry-proxy
  labels:
    {{- include "registryProxy.labels" . | nindent 4 }}
  {{- with .Values.registryProxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.registryProxy.service.type | default "LoadBalancer" }}
  sessionAffinity: None
  internalTrafficPolicy: Cluster
  externalTrafficPolicy: Cluster
  allocateLoadBalancerNodePorts: true
  ports:
    - port: {{ .Values.registryProxy.service.port | default 443 }}
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    {{- include "registryProxy.labels" . | nindent 4 }}
