apiVersion: v1
kind: Service
metadata:
  name: socket
  labels:
    {{- include "socket.labels" . | nindent 4 }}
spec:
  type: {{ .Values.socket.service.type | default "ClusterIP" }}
  sessionAffinity: None
  internalTrafficPolicy: Cluster
  ports:
    - port: {{ .Values.socket.service.port }}
      targetPort: {{ .Values.socket.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: socket
