{{- if .Values.watchtower.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchtower
  labels:
    {{- include "watchtower.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.watchtower.replicaCount }}
  selector:
    matchLabels:
      {{- include "watchtower.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "watchtower.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- include "chutes.podSecurityContext" . | nindent 8 }}
      {{- with .Values.watchtower.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.watchtower.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
        {{- include "chutes.defaultTolerations" . | nindent 8 }}
        {{- with .Values.watchtower.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        {{- include "chutes.redisCacertVolume" . | nindent 8 }}
      containers:
        - name: watchtower
          image: {{ include "chutes.image" (list . .Values.watchtower.image) | quote }}
          imagePullPolicy: {{ .Values.watchtower.imagePullPolicy }}
          securityContext:
            {{- include "chutes.containerSecurityContext" . | nindent 12 }}
          command:
            - uv
            - run
            - python
            - watchtower.py
          env:
            {{- include "chutes.sensitiveEnv" . | nindent 12 }}
            {{- include "chutes.commonEnv" . | nindent 12 }}
            {{- include "chutes.loggingEnv" . | nindent 12 }}
          volumeMounts:
            {{- include "chutes.redisCacertMount" . | nindent 12 }}
          resources:
            {{- toYaml .Values.watchtower.resources | nindent 12 }}
{{- end }}
